x-reusable-settings: &reusable-settings
  build:
    context: .
    dockerfile: ./backend.Dockerfile
  depends_on:
    postgres:
      condition: service_healthy
  env_file:
    - .env



services:
  api:
    <<: *reusable-settings
    container_name: backend_diary
    command: ./virtual-diary
    ports:
      - "8080:8080"


  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: